name: version_bump

on:
  workflow_dispatch:
    inputs:
      releaseKind:
        description: 'Kind of version bump'
        default: 'minor'
        type: choice
        options:
        - patch
        - minor
        - major
        required: true

jobs:
  build:
    name: version bump
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: 1.x

      - name: Run version bump
        run: |
          deno run -A https://deno.land/x/release_up/cli.ts --versionFile --changelog ${{github.event.inputs.releaseKind}} --dry
